import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import NavTab from './components/NavTab';
import './sass/main.scss';
import { AuthProvider } from './provider/AuthProvider';
import Header from './components/Header';



const poppins = Poppins({ subsets: ['latin'], weight: ['100', '500'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <Header></Header>
          {children}
          <NavTab></NavTab>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
