import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NavTab from "./components/NavTab";
import "./sass/main.scss";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        <NavTab></NavTab>
      </body>
    </html>
  );
};

export default RootLayout;
