
import { AuthProvider } from '@urbannerd/provider/AuthProvider';

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />x
      </head>
      <body>
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
